resolver: ghc-9.4.6

packages:
- .

extra-deps:
- hspec-2.11.4
- hspec-core-2.11.4
- hspec-discover-2.11.4
- hspec-expectations-0.8.4
- HUnit-1.6.2.0
- call-stack-0.4.0
- ansi-terminal-1.0
- ansi-terminal-types-0.11.5
- colour-2.3.6
- tf-random-0.5
- primitive-0.8.0.0
- quickcheck-io-0.2.0
- QuickCheck-2.14.3
- haskell-lexer-1.1.1
- random-1.2.1.1
- splitmix-0.1.0.4
- mtl-2.3.1
- git: https://github.com/Verification-for-Security/hrubric.git
  commit: f26a5f1f612ff58d1a0204b06cafa286ab74c077
